(block "}" @end) @indent
(node_body "}" @end) @indent
(edge_body "}" @end) @indent
(enum_body "}" @end) @indent
(trait_body "}" @end) @indent
(query_block "}" @end) @indent
(role_body_constraint_block "}" @end) @indent
(metadata_block "}" @end) @indent
(constraint_object "}" @end) @indent
(object_literal "}" @end) @indent
(union_variant "}" @end) @indent
(union_definition "}" @end) @indent
(access_role_definition "]" @end) @indent
(namespace_block "]" @end) @indent
(mixed_definition_batch "]" @end) @indent
(field_batch "]" @end) @indent
(node_batch "]" @end) @indent
(edge_batch "]" @end) @indent
(enum_batch "]" @end) @indent
(index_batch "]" @end) @indent
(create_node_batch "]" @end) @indent
(create_edge_batch "]" @end) @indent
(mixed_create_batch "]" @end) @indent
(bulk_alter_block "]" @end) @indent
(schema_definition "]" @end) @indent
(list_literal "]" @end) @indent
(function_call ")" @end) @indent
(subquery_expression ")" @end) @indent
(parenthesized_expression ")" @end) @indent ; If you add this to your grammar
